/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import java.util.Calendar;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author assparremberger
 */
public class ListClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListCidades
     */
    
    private JDesktopPane jdpTelaInicial;
    
    public ListClientes(JDesktopPane jdpTelaInicial) {
        initComponents();
        carregarTabela();
        this.jdpTelaInicial = jdpTelaInicial;
    }
    
    public void carregarTabela(){
        List<Cliente> lista = ClienteDAO.getClientes();
        String[] colunas = {"Código" , "Nome" , "Telefone" , "CPF" , "Data de Nascimento" , "Sexo" , "Casado?" , "Filhos?" , "Salário" , "Cidade" , "Estado"};
        
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(colunas); 
        
        for (Cliente cliente : lista) {
            String data = "" + 
                    cliente.getNascimento().get(Calendar.DAY_OF_MONTH) +
                    "/"+(cliente.getNascimento().get(Calendar.MONTH)+1) +
                    "/"+cliente.getNascimento().get(Calendar.YEAR);
            String casado = "Não";
            if( cliente.isCasado())
                casado = "Sim";
            String filhos = "Não";
            if( cliente.isTemFilhos())
                filhos = "Sim";
            String sexo = ""; 
            if( cliente.getSexo().equals("f"))
                sexo = "Feminino";
            if( cliente.getSexo().equals("m"))
                sexo = "Masculino";
            
            
            
            
            Object[] dados = {
                cliente.getCodigo(),
                cliente.getNome(),
                cliente.getTelefone(),
                cliente.getCpf(), data,
                sexo, casado, filhos, cliente.getSalario(),
                cliente.getCidade().getNome(),
                cliente.getCidade().getEstado().getNome()
                
                
                
                
            };
            model.addRow(dados);
        }
        tableClientes.setModel(model);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Clientes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Clientes");

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título 1", "Nome do Cliente"
            }
        ));
        jScrollPane1.setViewportView(tableClientes);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tableClientes.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Um cliente deve ser selecionado!");
        }else{
        int codigo = (int) tableClientes.getValueAt(linha, 0);
            Cliente cliente = ClienteDAO.getClienteByCodigo(codigo);
            
            int resposta = JOptionPane.showConfirmDialog(this, "Confirma a exclusão do cliente " + cliente.getNome()+"?", "Excluir Cliente", JOptionPane.YES_NO_OPTION);
            if( resposta == JOptionPane.YES_OPTION){
                ClienteDAO.excluir(cliente);
                carregarTabela();  
            }
           
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         int linha = tableClientes.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Um cliente deve ser selecionado!");
        }else{
        int codigo = (int) tableClientes.getValueAt(linha, 0); 
        FrmCliente tela = new FrmCliente(codigo, this);
        this.jdpTelaInicial.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
